In [18]:
import pandas as pd

In [537]:
df=pd.read_excel('NZ_Admin_JOBS.xlsx')

In [538]:
df.columns = ['Job_Title', 'Job_Link', 'Employer', 'Location','Time Of Post','Classification']

In [539]:
pd.set_option('display.max_colwidth',None)

In [540]:
df[df['Location'].str.contains(',')]

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification
12,Office Admin Assistant (10hrs per week),https://www.seek.co.nz/job/50597141?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,UIV Limited - Premier Insulation North Central,"location: AucklandAucklandarea: Manukau & East AucklandManukau & East Auckland,$20 per hour","8d ago,at",$20 per hour
17,Part-time Health & Disability Administrative Assistant,https://www.seek.co.nz/job/50610748?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,LIFEWISE,"location: AucklandAucklandarea: Auckland CentralAuckland Central,$20 - $24.99 per hour","6d ago,at",$20 - $24.99 per hour
23,Reception/Administrator,https://www.seek.co.nz/job/50556340?type=promoted#searchRequestToken=d16e02a9-8271-468a-abe3-04a22564a452,Fishing and Leisure Group Limited,"location: AucklandAucklandarea: Rodney & North ShoreRodney & North Shore,$19 to $22 per hour","Featured,at",$19 to $22 per hour
25,Office Administrator,https://www.seek.co.nz/job/50621389?type=standard#searchRequestToken=d16e02a9-8271-468a-abe3-04a22564a452,Brant Homes Limited,"location: AucklandAucklandarea: Manukau & East AucklandManukau & East Auckland,$20 - $24.99 per hour","4d ago,at",$20 - $24.99 per hour
36,office administrator,https://www.seek.co.nz/job/50621878?type=standard#searchRequestToken=d16e02a9-8271-468a-abe3-04a22564a452,Best Mates Pet Food,"location: WaikatoWaikatoarea: Rest of WaikatoRest of Waikato,$20 - $24.99 per hour","4d ago,at",$20 - $24.99 per hour
...,...,...,...,...,...,...
2700,Executive Assistant,https://www.seek.co.nz/job/50494228?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Robert Walters,"location: WellingtonWellington,Attractive remuneration","26d ago,at",Attractive remuneration
2701,Temporary Office Roles,https://www.seek.co.nz/job/50556279?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,"location: WaikatoWaikatoarea: HamiltonHamilton,Competitive hourly rates $$","14d ago,at",Competitive hourly rates $$
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,"location: WellingtonWellingtonarea: Wellington CentralWellington Central,Competitive hourly rate","27d ago,at",Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,"location: WaikatoWaikatoarea: HamiltonHamilton,Competitive hourly rates $$","20d ago,at",Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,"location: WaikatoWaikatoarea: HamiltonHamilton,Competitive hourly rates $$","28d ago,at",Competitive hourly rates $$

In [541]:
df[['Location','City']]=df['Location'].str.split(':',expand=True)[[1,2]]

In [542]:
df['Location']=df['Location'].str.split('area',expand=True)[0]

In [543]:
def deduplication(x):
    trim=x.strip()
    index = (trim+trim).find(trim,1)
    if index !=-1:
        return trim[:index]
    else:
        return trim

In [544]:
df['Location']=df['Location'].apply(deduplication)

In [545]:
df['City'].fillna(df['Location'],inplace=True)

In [546]:
df['City']=df['City'].apply(deduplication)

In [547]:
df.head()

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification,City
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,"Featured,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Office ManagementOffice Management,Tauranga
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,"Featured,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: ReceptionistsReceptionists,Tauranga
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,"4d ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: OtherOther,Auckland
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,"1h ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Administrative AssistantsAdministrative Assistants,Invercargill
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,"4d ago,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Client & Sales AdministrationClient & Sales Administration,Christchurch

In [548]:
df[['posted time','featurned at']] = df['Time Of Post'].str.split(',', expand = True)[[0,2]]

In [549]:
df.head()

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification,City,posted time,featurned at
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,"Featured,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Office ManagementOffice Management,Tauranga,Featured,Private Advertiser
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,"Featured,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: ReceptionistsReceptionists,Tauranga,Featured,None
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,"4d ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: OtherOther,Auckland,4d ago,None
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,"1h ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Administrative AssistantsAdministrative Assistants,Invercargill,1h ago,None
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,"4d ago,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Client & Sales AdministrationClient & Sales Administration,Christchurch,4d ago,Private Advertiser

In [550]:
def apply_salary(x):
    if 'classification:' in x:
        return 'unknown'
    else:
        return x

In [551]:
df['salary'] = df['Classification'].apply(apply_salary)

In [552]:
df

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,"Featured,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Office ManagementOffice Management,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,"Featured,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: ReceptionistsReceptionists,Tauranga,Featured,None,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,"4d ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: OtherOther,Auckland,4d ago,None,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,"1h ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Administrative AssistantsAdministrative Assistants,Invercargill,1h ago,None,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,"4d ago,at,Private Advertiser",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Client & Sales AdministrationClient & Sales Administration,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,"27d ago,at",classification: Administration & Office SupportAdministration & Office SupportsubClassification: Client & Sales AdministrationClient & Sales Administration,Auckland Central,27d ago,None,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,"27d ago,at",Competitive hourly rate,"Wellington CentralWellington Central,Competitive hourly rate",27d ago,None,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"20d ago,at",Competitive hourly rates $$,"HamiltonHamilton,Competitive hourly rates $$",20d ago,None,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"28d ago,at",Competitive hourly rates $$,"HamiltonHamilton,Competitive hourly rates $$",28d ago,None,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,"26d ago,at","classification: Administration & Office SupportAdministration & Office SupportsubClassification: PA, EA & SecretarialPA, EA & Secretarial",Wellington,26d ago,None,unknown

In [553]:
df['Classification']=df['Classification'].str.split('subClassification',expand=True)[0]

In [554]:
df['Classification']=df['Classification'].str.split(':',expand=True)[1]

In [555]:
df

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,"Featured,at,Private Advertiser",Administration & Office SupportAdministration & Office Support,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,"Featured,at",Administration & Office SupportAdministration & Office Support,Tauranga,Featured,None,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,"4d ago,at",Administration & Office SupportAdministration & Office Support,Auckland,4d ago,None,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,"1h ago,at",Administration & Office SupportAdministration & Office Support,Invercargill,1h ago,None,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,"4d ago,at,Private Advertiser",Administration & Office SupportAdministration & Office Support,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,"27d ago,at",Administration & Office SupportAdministration & Office Support,Auckland Central,27d ago,None,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,"27d ago,at",None,"Wellington CentralWellington Central,Competitive hourly rate",27d ago,None,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"20d ago,at",None,"HamiltonHamilton,Competitive hourly rates $$",20d ago,None,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"28d ago,at",None,"HamiltonHamilton,Competitive hourly rates $$",28d ago,None,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,"26d ago,at",Administration & Office SupportAdministration & Office Support,Wellington,26d ago,None,unknown

In [556]:
df['Classification'].fillna('unknown', inplace = True)

In [557]:
df['Classification']=df['Classification'].apply(deduplication)

In [558]:
df

,Job_Title,Job_Link,Employer,Location,Time Of Post,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,"Featured,at,Private Advertiser",Administration & Office Support,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,"Featured,at",Administration & Office Support,Tauranga,Featured,None,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,"4d ago,at",Administration & Office Support,Auckland,4d ago,None,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,"1h ago,at",Administration & Office Support,Invercargill,1h ago,None,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,"4d ago,at,Private Advertiser",Administration & Office Support,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,"27d ago,at",Administration & Office Support,Auckland Central,27d ago,None,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,"27d ago,at",unknown,"Wellington CentralWellington Central,Competitive hourly rate",27d ago,None,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"20d ago,at",unknown,"HamiltonHamilton,Competitive hourly rates $$",20d ago,None,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,"28d ago,at",unknown,"HamiltonHamilton,Competitive hourly rates $$",28d ago,None,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,"26d ago,at",Administration & Office Support,Wellington,26d ago,None,unknown

In [559]:
del df['Time Of Post']

In [560]:
df

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,Administration & Office Support,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,Administration & Office Support,Tauranga,Featured,None,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,Administration & Office Support,Auckland,4d ago,None,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,Administration & Office Support,Invercargill,1h ago,None,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,Administration & Office Support,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,Administration & Office Support,Auckland Central,27d ago,None,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,unknown,"Wellington CentralWellington Central,Competitive hourly rate",27d ago,None,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,"HamiltonHamilton,Competitive hourly rates $$",20d ago,None,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,"HamiltonHamilton,Competitive hourly rates $$",28d ago,None,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,Administration & Office Support,Wellington,26d ago,None,unknown

In [561]:
df['City']=df['City'].str.split(',',expand=True)[0]

In [562]:
df['City']=df['City'].apply(deduplication)

In [563]:
df

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Bay of Plenty,Administration & Office Support,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,Administration & Office Support,Tauranga,Featured,None,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,Administration & Office Support,Auckland,4d ago,None,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,Administration & Office Support,Invercargill,1h ago,None,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,NaN,Canterbury,Administration & Office Support,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,Administration & Office Support,Auckland Central,27d ago,None,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,unknown,Wellington Central,27d ago,None,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,20d ago,None,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,28d ago,None,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,Administration & Office Support,Wellington,26d ago,None,unknown

In [564]:
df['featurned at'].fillna('unknown', inplace = True)

In [565]:
df['Employer'].fillna(df['featurned at'], inplace = True)

In [566]:
df

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,featurned at,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Bay of Plenty,Administration & Office Support,Tauranga,Featured,Private Advertiser,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,Administration & Office Support,Tauranga,Featured,unknown,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,Administration & Office Support,Auckland,4d ago,unknown,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,Administration & Office Support,Invercargill,1h ago,unknown,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Canterbury,Administration & Office Support,Christchurch,4d ago,Private Advertiser,unknown
...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,Administration & Office Support,Auckland Central,27d ago,unknown,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,unknown,Wellington Central,27d ago,unknown,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,20d ago,unknown,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,28d ago,unknown,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,Administration & Office Support,Wellington,26d ago,unknown,unknown

In [567]:
del df['featurned at']

In [568]:
df['posted time']=df['posted time'].str.extract('(\d+[a-z])')

In [569]:
df['posted time'].fillna('unknown', inplace = True)

In [570]:
df[df['posted time'].str.contains('m')]

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,salary
5,Support Officer,https://www.seek.co.nz/job/50640393?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Ministry for Primary Industries,Northland,Administration & Office Support,Whangarei,9m,unknown
7,office administrator,https://www.seek.co.nz/job/50640166?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Hepburn Electrical Ltd,Bay of Plenty,Administration & Office Support,Rotorua,7m,unknown
146,Kaiāwhina Rau Tangata - Business Support Representative,https://www.seek.co.nz/job/50639878?type=standard#searchRequestToken=67323112-4f2b-4678-8f5f-9509324f14b1,Te Runanga o Ngai Tahu,Canterbury,Administration & Office Support,Christchurch,59m,unknown
248,Case Manager - Dynamic Case Manager role in Takapuna,https://www.seek.co.nz/job/50640451?type=standout#searchRequestToken=3997d218-20a4-4e1c-b282-a6a65db6abdb,NZDRC,Auckland,Administration & Office Support,Rodney & North Shore,7m,unknown
303,Team Admin,https://www.seek.co.nz/job/50640397?type=standout#searchRequestToken=08ea2732-ab51-473a-89d3-a5193b745fec,Madison Recruitment Limited,Wellington,Administration & Office Support,Hutt Valley,11m,unknown

In [571]:
df['posted time']=df['posted time'].astype('string')

In [572]:
def apply_posted_time(x):
    if 'd' in x:
        return int(x[:-1])
    if 'm' in x:
        return 'Less than one hour'
    if 'h' in x:
        return 'Less than one day'
    else:
        return 0

In [573]:
df['posted time']=df['posted time'].apply(apply_posted_time)

In [574]:
df

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Bay of Plenty,Administration & Office Support,Tauranga,0,unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,Administration & Office Support,Tauranga,0,unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,Administration & Office Support,Auckland,4,unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,Administration & Office Support,Invercargill,Less than one day,unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Canterbury,Administration & Office Support,Christchurch,4,unknown
...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,Administration & Office Support,Auckland Central,27,unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,unknown,Wellington Central,27,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,20,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,28,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,Administration & Office Support,Wellington,26,unknown

In [575]:
df[df['salary'].str.contains('\d',na=False)]['salary']

12                                            $20 per hour
17                                   $20 - $24.99 per hour
23                                     $19 to $22 per hour
25                                   $20 - $24.99 per hour
36                                   $20 - $24.99 per hour
42                                       $40,000 - $49,999
48                                            $25 per hour
58                             $60 000 - $70 000 per annum
59                                         $20.00 per hour
66                                   $20 - $24.99 per hour
75                                       $55,000 - $69,999
77                                        $20.00 per hour.
78                                   $20 - $24.99 per hour
81                                            $21 per hour
82                                       $55,000 - $64,999
89                         $50,000 - $55,000 plus benefits
97                                       $45,000 - $49,999
103                   $55,000 - $60,000 per annum pro rata
112                                  $20 - $24.99 per hour
114                                  $20 - $24.99 per hour
123                                      $48,835 - $63,221
134                                  $20 - $29.99 per hour
148                                                $24-$28
156                                            Up to $27ph
165                        $50,000 - $55,000 plus benefits
171                                  $20 - $29.99 per hour
173                                  $20 - $29.99 per hour
191                                  $20 - $24.99 per hour
201                                         8% holiday pay
212                                      $55,000 - $64,999
214                                      $40,000 - $49,999
219                                      $45,000 - $59,999
231                                 NZD25 - NZD28 per hour
247                                  $20 - $24.99 per hour
264                                      $45,000 - $49,999
277                                           $22 per hour
278                                     NZD75000 per annum
282                                  $20 - $24.99 per hour
306                                       $75k - $85k p.a.
311                            $24 - $25 + 8% holiday pay!
318                                      $40,000 - $49,999
319                                     $50,000 per annum.
346                                      $55,000 - $64,999
349                                     $20 - $25 per hour
379                                  $20 - $24.99 per hour
384                        $30 - $38 p.h. + 8% Holiday Pay
393                                            $45-$55,000
398                                      $50,000 - $54,999
403                      Up to $23 p.h. + + 8% Holiday Pay
405                                      Up to $22.00 p.h.
430          NZD69,726-94,127p.a.+Retirement contributions
442                     $60k-$70k depending on experience!
444                                    $22.00 - $23.00 phr
455                                      $40,000 - $49,999
458                        $27 - $33 p.h. + 8% holiday pay
459                       $60K - $80K experience dependent
464                                    $19 to $22 per hour
473     $60 - $65k + Career Progression to QS / leadership
478                                  $35 - $39.99 per hour
482                                      $55,000 - $64,999
494         $20 - $24.99 per hour dependent on experience.
503                        Up to $27 p.h. + 8% Holiday Pay
517                                  $20 - $24.99 per hour
530                                 NZD19 - NZD23 per hour
532                                             $60,000 pa
533                                      $40,000 - $49,999
536                        $21 - $25 p.h. + 8% Holiday Pay
546                                      $60,000 - $69,999
550                                       $21-$23 per hour
558                                      $50,000 - $59,999
560                                     $40 - $45 per hour
569                               $18.50 - $23.50 per hour
575                                                  $25.5
578                        Up to $35 p.h. + 8% Holiday Pay
579                        $21 - $22 p.h. + 8% Holiday Pay
582                                 NZD25 - NZD30 per hour
590                                  $25 - $29.99 per hour
612                                      $50,000 - $69,999
625                                      $50,000 - $59,999
629                                  $25 - $29.99 per hour
632                                      $50,000 - $64,999
633                                     $20 - $40 per hour
641                                      $48,000 - $55,000
644                      $50k - $65k p.a. + plus kiwisaver
650                                         $70-$80k+Super
653                                     $20 - $30 per hour
656                                      $45,000 - $54,999
660     $55,000 - $65,000 depending on relevant experience
663                                      $70-75k per annum
679              $45,000 - $55,000 depending on experience
682                       $24 - $28 p.h.  + 8% Holiday Pay
683                      $35 - $40 p.h. + + 8% Holiday Pay
695                                              Circa 50k
1936                      $24 - $28 p.h.  + 8% Holiday Pay
1937                     $35 - $40 p.h. + + 8% Holiday Pay
1949                                             Circa 50k
Name: salary, dtype: object

In [576]:
df['salary']=df[df['salary'].str.contains('\d', na=False)]['salary'].str.replace(' to ','-',regex=True)

In [577]:
df['salary'].fillna('unknown')

0       unknown
1       unknown
2       unknown
3       unknown
4       unknown
         ...
2703    unknown
2704    unknown
2705    unknown
2706    unknown
2707    unknown
Name: salary, Length: 2708, dtype: object

In [578]:
df['salary']=df[df['salary'].str.contains('\d', na=False)]['salary'].str.replace('\d\%','',regex=True)

In [579]:
df['salary']=df[df['salary'].str.contains('\d', na=False)]['salary'].str.replace(',','',regex=True)

In [580]:
df[df['salary'].str.contains('\d',na=False)]['salary'].head(50)

12                                    $20 per hour
17                           $20 - $24.99 per hour
23                                $19-$22 per hour
25                           $20 - $24.99 per hour
36                           $20 - $24.99 per hour
42                                 $40000 - $49999
48                                    $25 per hour
58                     $60 000 - $70 000 per annum
59                                 $20.00 per hour
66                           $20 - $24.99 per hour
75                                 $55000 - $69999
77                                $20.00 per hour.
78                           $20 - $24.99 per hour
81                                    $21 per hour
82                                 $55000 - $64999
89                   $50000 - $55000 plus benefits
97                                 $45000 - $49999
103             $55000 - $60000 per annum pro rata
112                          $20 - $24.99 per hour
114                          $20 - $24.99 per hour
123                                $48835 - $63221
134                          $20 - $29.99 per hour
148                                        $24-$28
156                                       Up-$27ph
165                  $50000 - $55000 plus benefits
171                          $20 - $29.99 per hour
173                          $20 - $29.99 per hour
191                          $20 - $24.99 per hour
212                                $55000 - $64999
214                                $40000 - $49999
219                                $45000 - $59999
231                         NZD25 - NZD28 per hour
247                          $20 - $24.99 per hour
264                                $45000 - $49999
277                                   $22 per hour
278                             NZD75000 per annum
282                          $20 - $24.99 per hour
306                               $75k - $85k p.a.
311                      $24 - $25 +  holiday pay!
318                                $40000 - $49999
319                              $50000 per annum.
346                                $55000 - $64999
349                             $20 - $25 per hour
379                          $20 - $24.99 per hour
384                  $30 - $38 p.h. +  Holiday Pay
393                                     $45-$55000
398                                $50000 - $54999
403                   Up-$23 p.h. + +  Holiday Pay
405                                 Up-$22.00 p.h.
430    NZD69726-94127p.a.+Retirement contributions
Name: salary, dtype: object

In [581]:
df[['low salary','high salary']] = df['salary'].str.split('-', n=1, expand = True).fillna('unknown')

In [582]:
df['low salary'] = df['low salary'].str.extract('(\d+\.\d+|\d+ \d+|\d+k|\d+)')
df['high salary'] = df['high salary'].str.extract('(\d+\.\d+|\d+ \d+|\d+k|\d+)')

In [583]:
df

,Job_Title,Job_Link,Employer,Location,Classification,City,posted time,salary,low salary,high salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Bay of Plenty,Administration & Office Support,Tauranga,0,NaN,NaN,NaN
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promoted#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Avenues Orthodontics,Bay of Plenty,Administration & Office Support,Tauranga,0,NaN,NaN,NaN
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,New Zealand Police,Auckland,Administration & Office Support,Auckland,4,NaN,NaN,NaN
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=standard#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Kew Pacific Island Early Learning Centre,Southland,Administration & Office Support,Invercargill,Less than one day,NaN,NaN,NaN
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=standout#searchRequestToken=feee129e-c80f-4f79-ac5f-98ddb6d6c22b,Private Advertiser,Canterbury,Administration & Office Support,Christchurch,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Hays Talent Solutions,Auckland,Administration & Office Support,Auckland Central,27,NaN,NaN,NaN
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,one eighty recruitment,Wellington,unknown,Wellington Central,27,NaN,NaN,NaN
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,20,NaN,NaN,NaN
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Asset Recruitment Ltd,Waikato,unknown,Hamilton,28,NaN,NaN,NaN
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=standout#searchRequestToken=c4e3452e-0c7b-47ee-8dcd-97b653d46ce8,Alpha Recruitment - NZ,Wellington,Administration & Office Support,Wellington,26,NaN,NaN,NaN

In [584]:
df[df['salary'].str.contains('\d',na=False)][['salary','low salary','high salary']].head(50)

                                          salary low salary high salary
12                                  $20 per hour         20         NaN
17                         $20 - $24.99 per hour         20       24.99
23                              $19-$22 per hour         19          22
25                         $20 - $24.99 per hour         20       24.99
36                         $20 - $24.99 per hour         20       24.99
42                               $40000 - $49999      40000       49999
48                                  $25 per hour         25         NaN
58                   $60 000 - $70 000 per annum     60 000      70 000
59                               $20.00 per hour      20.00         NaN
66                         $20 - $24.99 per hour         20       24.99
75                               $55000 - $69999      55000       69999
77                              $20.00 per hour.      20.00         NaN
78                         $20 - $24.99 per hour         20       24.99
81                                  $21 per hour         21         NaN
82                               $55000 - $64999      55000       64999
89                 $50000 - $55000 plus benefits      50000       55000
97                               $45000 - $49999      45000       49999
103           $55000 - $60000 per annum pro rata      55000       60000
112                        $20 - $24.99 per hour         20       24.99
114                        $20 - $24.99 per hour         20       24.99
123                              $48835 - $63221      48835       63221
134                        $20 - $29.99 per hour         20       29.99
148                                      $24-$28         24          28
156                                     Up-$27ph        NaN          27
165                $50000 - $55000 plus benefits      50000       55000
171                        $20 - $29.99 per hour         20       29.99
173                        $20 - $29.99 per hour         20       29.99
191                        $20 - $24.99 per hour         20       24.99
212                              $55000 - $64999      55000       64999
214                              $40000 - $49999      40000       49999
219                              $45000 - $59999      45000       59999
231                       NZD25 - NZD28 per hour         25          28
247                        $20 - $24.99 per hour         20       24.99
264                              $45000 - $49999      45000       49999
277                                 $22 per hour         22         NaN
278                           NZD75000 per annum      75000         NaN
282                        $20 - $24.99 per hour         20       24.99
306                             $75k - $85k p.a.        75k         85k
311                    $24 - $25 +  holiday pay!         24          25
318                              $40000 - $49999      40000       49999
319                            $50000 per annum.      50000         NaN
346                              $55000 - $64999      55000       64999
349                           $20 - $25 per hour         20          25
379                        $20 - $24.99 per hour         20       24.99
384                $30 - $38 p.h. +  Holiday Pay         30          38
393                                   $45-$55000         45       55000
398                              $50000 - $54999      50000       54999
403                 Up-$23 p.h. + +  Holiday Pay        NaN          23
405                               Up-$22.00 p.h.        NaN       22.00
430  NZD69726-94127p.a.+Retirement contributions      69726       94127

In [585]:
df['low salary'] = df[df['low salary'].str.contains('\d', na=False)]['low salary'].str.replace('k', '000', regex=True)
df['high salary'] = df[df['high salary'].str.contains('\d', na=False)]['high salary'].str.replace('k', '000', regex=True)

In [586]:
pd.set_option('display.max_rows', 500)
df[df['low salary'].str.contains('\d',na=False)]['low salary'].head(100)

12          20
17          20
23          19
25          20
36          20
42       40000
48          25
58      60 000
59       20.00
66          20
75       55000
77       20.00
78          20
81          21
82       55000
89       50000
97       45000
103      55000
112         20
114         20
123      48835
134         20
148         24
165      50000
171         20
173         20
191         20
212      55000
214      40000
219      45000
231         25
247         20
264      45000
277         22
278      75000
282         20
306      75000
311         24
318      40000
319      50000
346      55000
349         20
379         20
384         30
393         45
398      50000
430      69726
442      60000
444      22.00
455      40000
458         27
459         60
464         19
473         60
478         35
482      55000
494         20
517         20
530         19
532      60000
533      40000
536         21
546      60000
550         21
558      50000
560         40
569      18.50
575       25.5
579         21
582         25
590         25
612      50000
625      50000
629         25
632      50000
633         20
641      48000
644      50000
650         70
653         20
656      45000
660      55000
663         70
679      45000
682         24
683         35
695      50000
1936        24
1937        35
1949     50000
Name: low salary, dtype: object

In [587]:
df[df['salary'].str.contains('\d',na=False)][['salary','low salary','high salary']].head(50)

                                          salary low salary high salary
12                                  $20 per hour         20         NaN
17                         $20 - $24.99 per hour         20       24.99
23                              $19-$22 per hour         19          22
25                         $20 - $24.99 per hour         20       24.99
36                         $20 - $24.99 per hour         20       24.99
42                               $40000 - $49999      40000       49999
48                                  $25 per hour         25         NaN
58                   $60 000 - $70 000 per annum     60 000      70 000
59                               $20.00 per hour      20.00         NaN
66                         $20 - $24.99 per hour         20       24.99
75                               $55000 - $69999      55000       69999
77                              $20.00 per hour.      20.00         NaN
78                         $20 - $24.99 per hour         20       24.99
81                                  $21 per hour         21         NaN
82                               $55000 - $64999      55000       64999
89                 $50000 - $55000 plus benefits      50000       55000
97                               $45000 - $49999      45000       49999
103           $55000 - $60000 per annum pro rata      55000       60000
112                        $20 - $24.99 per hour         20       24.99
114                        $20 - $24.99 per hour         20       24.99
123                              $48835 - $63221      48835       63221
134                        $20 - $29.99 per hour         20       29.99
148                                      $24-$28         24          28
156                                     Up-$27ph        NaN          27
165                $50000 - $55000 plus benefits      50000       55000
171                        $20 - $29.99 per hour         20       29.99
173                        $20 - $29.99 per hour         20       29.99
191                        $20 - $24.99 per hour         20       24.99
212                              $55000 - $64999      55000       64999
214                              $40000 - $49999      40000       49999
219                              $45000 - $59999      45000       59999
231                       NZD25 - NZD28 per hour         25          28
247                        $20 - $24.99 per hour         20       24.99
264                              $45000 - $49999      45000       49999
277                                 $22 per hour         22         NaN
278                           NZD75000 per annum      75000         NaN
282                        $20 - $24.99 per hour         20       24.99
306                             $75k - $85k p.a.      75000       85000
311                    $24 - $25 +  holiday pay!         24          25
318                              $40000 - $49999      40000       49999
319                            $50000 per annum.      50000         NaN
346                              $55000 - $64999      55000       64999
349                           $20 - $25 per hour         20          25
379                        $20 - $24.99 per hour         20       24.99
384                $30 - $38 p.h. +  Holiday Pay         30          38
393                                   $45-$55000         45       55000
398                              $50000 - $54999      50000       54999
403                 Up-$23 p.h. + +  Holiday Pay        NaN          23
405                               Up-$22.00 p.h.        NaN       22.00
430  NZD69726-94127p.a.+Retirement contributions      69726       94127

In [588]:
df['low salary'].fillna(df['high salary'], inplace = True)

In [589]:
df['high salary'].fillna(df['low salary'], inplace = True)

In [590]:
df['per hr/annum'] = df['salary'].str.split('per', expand = True)[1]

In [591]:
df[df['salary'].str.contains('\d',na=False)][['salary','low salary','high salary','per hr/annum']].head(50)

,salary,low salary,high salary,per hr/annum
12,$20 per hour,20,20,hour
17,$20 - $24.99 per hour,20,24.99,hour
23,$19-$22 per hour,19,22,hour
25,$20 - $24.99 per hour,20,24.99,hour
36,$20 - $24.99 per hour,20,24.99,hour
42,$40000 - $49999,40000,49999,None
48,$25 per hour,25,25,hour
58,$60 000 - $70 000 per annum,60 000,70 000,annum
59,$20.00 per hour,20.00,20.00,hour
66,$20 - $24.99 per hour,20,24.99,hour
75,$55000 - $69999,55000,69999,None
77,$20.00 per hour.,20.00,20.00,hour.
78,$20 - $24.99 per hour,20,24.99,hour
81,$21 per hour,21,21,hour
82,$55000 - $64999,55000,64999,None
89,$50000 - $55000 plus benefits,50000,55000,None
97,$45000 - $49999,45000,49999,None
103,$55000 - $60000 per annum pro rata,55000,60000,annum pro rata
112,$20 - $24.99 per hour,20,24.99,hour
114,$20 - $24.99 per hour,20,24.99,hour
123,$48835 - $63221,48835,63221,None
134,$20 - $29.99 per hour,20,29.99,hour
148,$24-$28,24,28,None
156,Up-$27ph,27,27,None
165,$50000 - $55000 plus benefits,50000,55000,None
171,$20 - $29.99 per hour,20,29.99,hour
173,$20 - $29.99 per hour,20,29.99,hour
191,$20 - $24.99 per hour,20,24.99,hour
212,$55000 - $64999,55000,64999,None
214,$40000 - $49999,40000,49999,None
219,$45000 - $59999,45000,59999,None
231,NZD25 - NZD28 per hour,25,28,hour
247,$20 - $24.99 per hour,20,24.99,hour
264,$45000 - $49999,45000,49999,None
277,$22 per hour,22,22,hour
278,NZD75000 per annum,75000,75000,annum
282,$20 - $24.99 per hour,20,24.99,hour
306,$75k - $85k p.a.,75000,85000,None
311,$24 - $25 + holiday pay!,24,25,None
318,$40000 - $49999,40000,49999,None
319,$50000 per annum.,50000,50000,annum.
346,$55000 - $64999,55000,64999,None
349,$20 - $25 per hour,20,25,hour
379,$20 - $24.99 per hour,20,24.99,hour
384,$30 - $38 p.h. + Holiday Pay,30,38,None
393,$45-$55000,45,55000,None
398,$50000 - $54999,50000,54999,None
403,Up-$23 p.h. + + Holiday Pay,23,23,None
405,Up-$22.00 p.h.,22.00,22.00,None
430,NZD69726-94127p.a.+Retirement contributions,69726,94127,None

In [592]:
df['per hr/annum'].fillna('unknown')

0       unknown
1       unknown
2       unknown
3       unknown
4       unknown
         ...
2703    unknown
2704    unknown
2705    unknown
2706    unknown
2707    unknown
Name: per hr/annum, Length: 2708, dtype: object

In [593]:
df['per hr/annum']=df['per hr/annum'].astype('string')

In [594]:
def apply_per_hr(x):
    if x.str.contains('\dd'):
        return 'hour'
    if x.str.contains('\ddddd'):
        return 'annum'
    else:
        return 0

In [595]:
df['per hr/annum']=df['per hr/annum'].apply(apply_per_hr)

AttributeError: 'NAType' object has no attribute 'str'